name: Blog Post Automation

on:
  push:
    branches:
      - master

jobs:
  process-blogs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install node-fetch front-matter

      - name: Run Blog Publisher Script
        run: node blogPublisher.js
        env:
          DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}

      - name: Run Blog Updater Script
        run: node blogUpdater.js
        env:
          DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}
